# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-27 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('mianfei', '\u514d\u8d39'), ('soufei', '\u6536\u8d39')], default='soufei', max_length=20, verbose_name='\u6536\u8d39\u7c7b\u522b'),
        ),
    ]
