# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taoker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OraginData',
            new_name='OriginData',
        ),
    ]
