# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taoker', '0002_auto_20170309_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='origindata',
            name='image',
            field=models.ImageField(default='', upload_to='taoke_data/%Y/%m', verbose_name='\u5546\u54c1\u9996\u56fe'),
        ),
    ]
