# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taoker', '0003_origindata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origindata',
            name='url',
            field=models.URLField(default='', verbose_name='\u4e0a\u5bb6\u5730\u5740'),
        ),
    ]
