# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taoker', '0004_auto_20170309_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origindata',
            name='image',
            field=models.ImageField(default='', upload_to='taoke_data/oragin/%Y/%m', verbose_name='\u5546\u54c1\u9996\u56fe'),
        ),
    ]
