# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 17:04
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taoker', '0006_service_servicebuylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceUseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taoker.Service', verbose_name='\u8d2d\u4e70\u7684\u670d\u52a1')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u6dd8\u5ba2\u670d\u52a1\u4f7f\u7528\u8bb0\u5f55',
                'verbose_name_plural': '\u6dd8\u5ba2\u670d\u52a1\u4f7f\u7528\u8bb0\u5f55',
            },
        ),
    ]
