# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 23:59
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoodAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodurl', models.URLField(default='', verbose_name='\u4e0a\u5bb6\u5730\u5740')),
                ('goodaddprice', models.IntegerField(default=50, verbose_name='\u5546\u54c1\u52a0\u4ef7')),
                ('goodtitle', models.CharField(max_length=50, verbose_name='\u5546\u54c1\u6807\u9898')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('has_download', models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e0b\u8f7d\u5904\u7406')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u63d0\u4ea4\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u5236\u6570\u636e\u5305\u8bf7\u6c42',
                'verbose_name_plural': '\u5236\u6570\u636e\u5305\u8bf7\u6c42',
            },
        ),
    ]
