# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 00:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_usergoodask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergoodask',
            name='has_download',
        ),
        migrations.RemoveField(
            model_name='usergoodask',
            name='user',
        ),
    ]
