# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 16:47
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0003_auto_20170310_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTitleAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_keyword', models.CharField(max_length=200, verbose_name='\u6807\u9898\u5173\u952e\u5b57')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u83b7\u53d6\u6807\u9898\u8bf7\u6c42',
                'verbose_name_plural': '\u83b7\u53d6\u6807\u9898\u8bf7\u6c42',
            },
        ),
    ]
