# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_usertitleask'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertitleask',
            name='titles',
            field=models.TextField(default='', max_length=65532, verbose_name='\u6807\u9898\u5217\u8868'),
        ),
    ]
