# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 13:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0005_usertitleask_titles'),
    ]

    operations = [
        migrations.CreateModel(
            name='LieBianData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_code', models.CharField(max_length=100, verbose_name='\u5546\u5bb6\u7f16\u7801')),
                ('download', models.FileField(upload_to='course/resource/%Y/%m', verbose_name='\u88c2\u53d8\u6570\u636e\u5305')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u5217\u53d8\u6570\u636e\u5305',
                'verbose_name_plural': '\u5217\u53d8\u6570\u636e\u5305',
            },
        ),
    ]
