# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_liebiandata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liebiandata',
            name='download',
            field=models.FileField(upload_to='taoke_data/fenlie', verbose_name='\u88c2\u53d8\u6570\u636e\u5305'),
        ),
    ]
