# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_oragindata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OraginData',
        ),
    ]
