# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170311_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='qq',
            field=models.CharField(default='', max_length=12, verbose_name='qq\u53f7'),
        ),
    ]
